#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$DIR/bin/rpc/tl-rpc" ]; then
    exec "$DIR/bin/rpc/tl-rpc" "$@"
else
    exec dotnet "$DIR/bin/rpc/tl-rpc.dll" "$@"
fi
