<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Thallium.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Thallium.Core\Benchmarks.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Thallium.Core\Thallium.Core.fsproj" />
  </ItemGroup>

</Project>
